// Shared assessment data — profiles, season descriptions, scoring helpers

export const seasonDescriptions: Record<string, string> = {
  Identity:       "Building the foundation — clarifying who you are, what you believe, and how you connect with others.",
  Exploration:    "Getting reps — trying things widely, taking on responsibility, learning what fits and what doesn't.",
  Influence:      "Going deep — focused, in your lane, using your expertise and passion to make a specific difference.",
  Multiplication: "Passing it on — investing in others, giving away what you've built, multiplying your impact through people.",
};

export const profiles: Record<string, {name: string; mirrorLine: string; description: string; question: string}> = {
  Identity_Behind:        {name:"Foundation",        mirrorLine:"You're in the foundation season, but you haven't started building yet.",                 description:"Something is keeping you from the work of this season — whether that's distraction, discomfort, or just not knowing where to start. The foundation isn't optional. It's not something you come back and build later. The good news is that you're not behind — you're here, and here is exactly where this starts.",                                                                                         question:"What would I need to believe about myself to actually begin?"},
  Identity_Aligned:       {name:"Groundwork",        mirrorLine:"You're doing the hardest work there is — and it doesn't look like much yet.",             description:"The foundation season is easy to underestimate, mostly because it's invisible. Nobody builds a house because they're excited about concrete. But without what gets built here — a clear sense of who you are, what you believe, how you connect — everything else wobbles. You're in it. Stay in it.",                                                                                                          question:"What do I believe about myself that I haven't said out loud yet?"},
  Identity_Ahead:         {name:"Ahead of Yourself", mirrorLine:"You're reaching for influence before the foundation is ready to hold it.",                 description:"The ambition is real, and there's nothing wrong with it. But the drive to get to the next thing is moving faster than the work of this season. What gets skipped here doesn't disappear — it shows up later, under more pressure, with higher stakes. The fastest way forward right now is to slow down enough to build something that holds.",                                                               question:"What am I hoping to skip, and what will it cost me later?"},
  Exploration_Behind:     {name:"Waiting to Launch", mirrorLine:"You're in a season built for saying yes — and you keep saying not yet.",                   description:"Exploration is the one season where playing it safe is the riskiest thing you can do. The whole point is to get reps, try things, and learn from what doesn't work. Waiting for the right opportunity, the right moment, or the right level of readiness is a way of staying comfortable in a season designed for discomfort. The reps don't come to you.",                                                question:"What would I try if I knew failure wasn't the worst outcome?"},
  Exploration_Aligned:    {name:"Wide Open",         mirrorLine:"You're fully in the middle of it — and it's supposed to feel this way.",                   description:"Exploration is the most misunderstood season. From the outside it looks scattered. From the inside it can feel like falling behind. It's neither. You're building the dots you'll connect later. The work of this season isn't to find your lane — it's to earn the right to pick one. Keep going.",                                                                                           question:"What am I learning about myself that I couldn't have learned any other way?"},
  Exploration_Ahead:      {name:"Ready to Land",     mirrorLine:"You're trying to land the plane before you've mapped the territory.",                       description:"There's a pull toward focus, toward picking a lane, toward being done with the wandering. That's understandable — but it's early. Forcing a conclusion in this season produces answers that feel right for about six months. The jello hasn't set yet. The explorers who resist the urge to narrow too soon are the ones who enter Influence with real authority.",                                             question:"What am I afraid I'll find if I keep exploring?"},
  Influence_Behind:       {name:"More to Give",      mirrorLine:"You've earned the right to narrow — you're just not using it yet.",                         description:"You're in the season of focus but still operating like an explorer. Still saying yes to too much, still spreading across too many directions. The reps are done. The season has changed. Staying in wide-open mode now isn't humility — it's avoidance. You have something specific to offer. The world needs you to offer it specifically.",                                                        question:"What would I stop doing tomorrow if I actually trusted what I'm good at?"},
  Influence_Aligned:      {name:"In the Pocket",     mirrorLine:"Your season, your expertise, and your passion are unusually well-aligned right now.",       description:"That's rare and worth acknowledging. The risk for people in this position isn't falling behind — it's coasting. Integration can quietly become complacency. The question worth sitting with isn't what do I need to fix. It's what do I need to protect.",                                                                                                                                     question:"What would I do with my time if I stopped doing everything out of obligation?"},
  Influence_Ahead:        {name:"Running on Fumes",  mirrorLine:"You're thinking about giving it away before you've fully used it.",                         description:"There's a pull toward the next season — toward mentoring, stepping back, letting others lead. That's worth paying attention to. But it's worth asking whether that pull is coming from wisdom or exhaustion. Multiplication is a season, not an escape. The most effective multipliers finished their season of Influence before they moved on.",                                                    question:"Am I ready to step back, or am I just tired?"},
  Multiplication_Behind:  {name:"Holding the Reins", mirrorLine:"You're in the season of passing it on — and you're still holding on.",                     description:"The transition out of Influence is the hardest one. The work is familiar, the role is comfortable, and letting go feels like loss. But the window to make this transition gracefully doesn't stay open forever. The people behind you need what you know more than they need you to stay in charge. What looks like loyalty to the work may be costing the mission.",                             question:"What am I holding onto — and who is it actually serving?"},
  Multiplication_Aligned: {name:"Passing It On",     mirrorLine:"The shift you've made is rarer than you think — and more important than it looks.",         description:"Most people in your position either hang on too long or check out entirely. You're doing something harder than both — staying engaged differently. Your energy goes into people now, not output. That's not a step down. It's the season with the longest reach. What you invest in others will outlast almost anything you could have done yourself.",                                           question:"Who is a season or two behind me that I haven't made time for yet?"},
  Multiplication_Ahead:   {name:"Not Done Yet",      mirrorLine:"You've mentally moved on before this season is finished.",                                  description:"There's a version of checking out that looks like wisdom from the outside. It has the right vocabulary — legacy, investment, stepping back. But it's still checking out. Multiplication is not retirement. There's still significant work to do, and you're in a position few people ever reach. The question isn't whether you've earned the right to slow down. It's whether slowing down is what this season actually needs from you.", question:"What would I regret not doing while I still have the energy and the access to do it?"},
};

export function lookupProfile(season: string, profileName: string) {
  // Find profile by name match first, then fall back to season_Aligned
  const entry = Object.values(profiles).find(p => p.name === profileName);
  if (entry) return entry;
  return profiles[`${season}_Aligned`] || { name: profileName, mirrorLine: "", description: "", question: "" };
}
